/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package licencias_tamps;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio Sosa
 */
public class cuestionario extends javax.swing.JFrame {

    /**
     * Creates new form cuestionario
     */
     Statement stm,stm1,stm2,stm3;
     ResultSet rs1,rs;
    
    public cuestionario() {
        initComponents();

           ImageIcon imagen = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("RO-2A.jpg")));
        Image img=imagen.getImage();
        Image img1=img.getScaledInstance(ceda24.getWidth(),ceda24.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img1);
        ceda24.setIcon(i);
          ImageIcon imagen1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Ceda el paso.jpg")));
        Image img12=imagen1.getImage();
        Image img11=img12.getScaledInstance(ceda25.getWidth(),ceda25.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(img11);
        ceda25.setIcon(i2);
//            ImageIcon i = new ImageIcon("Ceda el paso.jpg");
//            Image image1 = i.getImage().getScaledInstance(ceda26.getWidth(), ceda26.getHeight(), Image.SCALE_SMOOTH);
//            ceda26.setIcon(new ImageIcon(image));
    }
    
 ButtonGroup g1 = new ButtonGroup();
 ButtonGroup g2 = new ButtonGroup();
 ButtonGroup g3 = new ButtonGroup();
 ButtonGroup g4 = new ButtonGroup();
 ButtonGroup g5 = new ButtonGroup();
 ButtonGroup g6 = new ButtonGroup();
 ButtonGroup g7 = new ButtonGroup();
 ButtonGroup g8 = new ButtonGroup();
 ButtonGroup g9 = new ButtonGroup();
 ButtonGroup g10 = new ButtonGroup();
 ButtonGroup g11 = new ButtonGroup();
 ButtonGroup g12 = new ButtonGroup();
 ButtonGroup g13 = new ButtonGroup();
 ButtonGroup g14 = new ButtonGroup();
 ButtonGroup g15 = new ButtonGroup();
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel283 = new javax.swing.JLabel();
        jLabel284 = new javax.swing.JLabel();
        jRadioButton236 = new javax.swing.JRadioButton();
        jRadioButton237 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jLabel285 = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        jRadioButton238 = new javax.swing.JRadioButton();
        jRadioButton239 = new javax.swing.JRadioButton();
        jLabel287 = new javax.swing.JLabel();
        jLabel288 = new javax.swing.JLabel();
        jRadioButton240 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jLabel289 = new javax.swing.JLabel();
        jLabel290 = new javax.swing.JLabel();
        jRadioButton241 = new javax.swing.JRadioButton();
        jRadioButton242 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jLabel291 = new javax.swing.JLabel();
        jLabel292 = new javax.swing.JLabel();
        jRadioButton243 = new javax.swing.JRadioButton();
        jRadioButton244 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jLabel293 = new javax.swing.JLabel();
        jLabel294 = new javax.swing.JLabel();
        jRadioButton245 = new javax.swing.JRadioButton();
        jRadioButton246 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        jLabel295 = new javax.swing.JLabel();
        jLabel296 = new javax.swing.JLabel();
        r7 = new javax.swing.JRadioButton();
        jRadioButton247 = new javax.swing.JRadioButton();
        jRadioButton248 = new javax.swing.JRadioButton();
        jLabel297 = new javax.swing.JLabel();
        jLabel298 = new javax.swing.JLabel();
        jRadioButton249 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        jRadioButton250 = new javax.swing.JRadioButton();
        jLabel299 = new javax.swing.JLabel();
        jLabel300 = new javax.swing.JLabel();
        r9 = new javax.swing.JRadioButton();
        jRadioButton251 = new javax.swing.JRadioButton();
        jRadioButton252 = new javax.swing.JRadioButton();
        jLabel301 = new javax.swing.JLabel();
        jLabel302 = new javax.swing.JLabel();
        r10 = new javax.swing.JRadioButton();
        jRadioButton253 = new javax.swing.JRadioButton();
        jRadioButton254 = new javax.swing.JRadioButton();
        jLabel303 = new javax.swing.JLabel();
        jLabel304 = new javax.swing.JLabel();
        jRadioButton255 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        jRadioButton256 = new javax.swing.JRadioButton();
        jLabel305 = new javax.swing.JLabel();
        jLabel306 = new javax.swing.JLabel();
        r12 = new javax.swing.JRadioButton();
        jRadioButton257 = new javax.swing.JRadioButton();
        jRadioButton258 = new javax.swing.JRadioButton();
        jLabel307 = new javax.swing.JLabel();
        jLabel308 = new javax.swing.JLabel();
        jRadioButton259 = new javax.swing.JRadioButton();
        r13 = new javax.swing.JRadioButton();
        jRadioButton260 = new javax.swing.JRadioButton();
        jLabel309 = new javax.swing.JLabel();
        jLabel310 = new javax.swing.JLabel();
        jRadioButton261 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        jRadioButton262 = new javax.swing.JRadioButton();
        jLabel311 = new javax.swing.JLabel();
        jLabel312 = new javax.swing.JLabel();
        jRadioButton263 = new javax.swing.JRadioButton();
        jRadioButton264 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        jLabel313 = new javax.swing.JLabel();
        jLabel314 = new javax.swing.JLabel();
        jLabel315 = new javax.swing.JLabel();
        jLabel316 = new javax.swing.JLabel();
        jLabel317 = new javax.swing.JLabel();
        ceda24 = new javax.swing.JLabel();
        ceda25 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        curp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(616, 3000));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel283.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel283.setForeground(new java.awt.Color(0, 0, 0));
        jLabel283.setText("Pregunta 1");

        jLabel284.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel284.setForeground(new java.awt.Color(0, 0, 0));
        jLabel284.setText("¿Quien cuenta con mayor prioridad en la jerarquia vial?");

        buttonGroup1.add(jRadioButton236);
        jRadioButton236.setText("Automovilista");

        buttonGroup1.add(jRadioButton237);
        jRadioButton237.setText("Ciclista");

        buttonGroup1.add(r1);
        r1.setText("Peaton");

        jLabel285.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel285.setForeground(new java.awt.Color(0, 0, 0));
        jLabel285.setText("Pregunta 2");

        jLabel286.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel286.setForeground(new java.awt.Color(0, 0, 0));
        jLabel286.setText("¿En que situación puedes manipular tu celular dentro del vehiculo?");

        buttonGroup2.add(r2);
        r2.setText("Cuando el vehiculo esta detenido");

        buttonGroup2.add(jRadioButton238);
        jRadioButton238.setText("Cuando el vehiculo esta sobre una vía lenta ");

        buttonGroup2.add(jRadioButton239);
        jRadioButton239.setText("Cuando el vehiculo avanza a menos de 20 km/h");

        jLabel287.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel287.setForeground(new java.awt.Color(0, 0, 0));
        jLabel287.setText("Pregunta 3");

        jLabel288.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel288.setForeground(new java.awt.Color(0, 0, 0));
        jLabel288.setText("Cuando un semaforo se encuentra apagado,");

        buttonGroup3.add(jRadioButton240);
        jRadioButton240.setText("Los que buscan acceder a la via primaria");
        jRadioButton240.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroup3.add(r3);
        r3.setText("Los que cicrculan por la via primaria");

        jLabel289.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel289.setForeground(new java.awt.Color(0, 0, 0));
        jLabel289.setText("Pregunta 4");

        jLabel290.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel290.setForeground(new java.awt.Color(0, 0, 0));
        jLabel290.setText("¿Cual es la velocidad máxima cuando se avanza en zonas escolares?");

        buttonGroup4.add(jRadioButton241);
        jRadioButton241.setText("30 km/h");

        buttonGroup4.add(jRadioButton242);
        jRadioButton242.setText("10 km/h");
        jRadioButton242.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        buttonGroup4.add(r4);
        r4.setText("20 km/h");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res4ActionPerformed(evt);
            }
        });

        jLabel291.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel291.setForeground(new java.awt.Color(0, 0, 0));
        jLabel291.setText("Pregunta 5");

        jLabel292.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel292.setForeground(new java.awt.Color(0, 0, 0));
        jLabel292.setText("¿Por cual lado se debe rebasar a otro vehiculo?");

        buttonGroup5.add(jRadioButton243);
        jRadioButton243.setText("Izquierdo");

        buttonGroup5.add(jRadioButton244);
        jRadioButton244.setText("Ambos");

        buttonGroup5.add(r5);
        r5.setText("Ninguno");

        jLabel293.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel293.setForeground(new java.awt.Color(0, 0, 0));
        jLabel293.setText("Pregunta 6");

        jLabel294.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel294.setForeground(new java.awt.Color(0, 0, 0));
        jLabel294.setText("¿Cual es la velocidad maxima para avanzar en los carriles centrales");

        buttonGroup6.add(jRadioButton245);
        jRadioButton245.setText("60 km/h");

        buttonGroup6.add(jRadioButton246);
        jRadioButton246.setText("50 km/h");

        buttonGroup6.add(r6);
        r6.setText("80 km/h");

        jLabel295.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel295.setForeground(new java.awt.Color(0, 0, 0));
        jLabel295.setText("Pregunta 7");

        jLabel296.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel296.setForeground(new java.awt.Color(0, 0, 0));
        jLabel296.setText("¿Hacia que dirección esta permitida la vuelta continua cuando no");

        buttonGroup7.add(r7);
        r7.setText("Ninguna de las dos");

        buttonGroup7.add(jRadioButton247);
        jRadioButton247.setText("Derecha");

        buttonGroup7.add(jRadioButton248);
        jRadioButton248.setText("Izquierda");

        jLabel297.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel297.setForeground(new java.awt.Color(0, 0, 0));
        jLabel297.setText("Pregunta 8");

        jLabel298.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel298.setForeground(new java.awt.Color(0, 0, 0));
        jLabel298.setText("¿Que vehiculos no estan excentos del programa hoy no circula?");

        buttonGroup8.add(jRadioButton249);
        jRadioButton249.setText("De emergencia");

        buttonGroup8.add(r8);
        r8.setText("Compactos");

        buttonGroup8.add(jRadioButton250);
        jRadioButton250.setText("Electricos");

        jLabel299.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel299.setForeground(new java.awt.Color(0, 0, 0));
        jLabel299.setText("Pregunta 9");

        jLabel300.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel300.setForeground(new java.awt.Color(0, 0, 0));
        jLabel300.setText("¿Cual es la velocidad máxima para avanzar por una vía primaria?");

        buttonGroup9.add(r9);
        r9.setText("50 km/h");

        buttonGroup9.add(jRadioButton251);
        jRadioButton251.setText("60 km/h");

        buttonGroup9.add(jRadioButton252);
        jRadioButton252.setText("80 km/h");
        jRadioButton252.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        jLabel301.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel301.setForeground(new java.awt.Color(0, 0, 0));
        jLabel301.setText("Pregunta 10");

        jLabel302.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel302.setForeground(new java.awt.Color(0, 0, 0));
        jLabel302.setText("¿Quienes deben utilizar el cinturon de seguridad?");

        buttonGroup10.add(r10);
        r10.setText("Todos los pasajeros");

        buttonGroup10.add(jRadioButton253);
        jRadioButton253.setText("El conductor");

        buttonGroup10.add(jRadioButton254);
        jRadioButton254.setText("El conductor y el copiloto");

        jLabel303.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel303.setForeground(new java.awt.Color(0, 0, 0));
        jLabel303.setText("Pregunta 11");

        jLabel304.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel304.setForeground(new java.awt.Color(0, 0, 0));
        jLabel304.setText("¿En que situación puedes llevar a tu perro sentado en tus piernas");

        buttonGroup11.add(jRadioButton255);
        jRadioButton255.setText("Dias festivos y sabados de 8:00 am a 11:00 am ");

        buttonGroup11.add(r11);
        r11.setText("Nunca");

        buttonGroup11.add(jRadioButton256);
        jRadioButton256.setText("Cuando avanzas sobre la via de transito lento");

        jLabel305.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel305.setForeground(new java.awt.Color(0, 0, 0));
        jLabel305.setText("Pregunta 12");

        jLabel306.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel306.setForeground(new java.awt.Color(0, 0, 0));
        jLabel306.setText("¿No puedes circular si el nivel de alcohol en tu sangre es mayor a?");

        buttonGroup12.add(r12);
        r12.setText("0.8 gramos por litro");
        r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res12ActionPerformed(evt);
            }
        });

        buttonGroup12.add(jRadioButton257);
        jRadioButton257.setText("8 gramos por litro");

        buttonGroup12.add(jRadioButton258);
        jRadioButton258.setText("80 gramos por litro");

        jLabel307.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel307.setForeground(new java.awt.Color(0, 0, 0));
        jLabel307.setText("Pregunta 13");

        jLabel308.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel308.setForeground(new java.awt.Color(0, 0, 0));
        jLabel308.setText("¿Cual es la distancia máxima en la que puede quedar un auto");

        buttonGroup13.add(jRadioButton259);
        jRadioButton259.setText("Un metro");

        buttonGroup13.add(r13);
        r13.setText("30 cm");

        buttonGroup13.add(jRadioButton260);
        jRadioButton260.setText("2 metros");

        jLabel309.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel309.setForeground(new java.awt.Color(0, 0, 0));
        jLabel309.setText("Pregunta 14");

        jLabel310.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel310.setForeground(new java.awt.Color(0, 0, 0));
        jLabel310.setText("¿Que significa este simbolo?");

        buttonGroup14.add(jRadioButton261);
        jRadioButton261.setText("Ceda el paso");

        buttonGroup14.add(r14);
        r14.setText("Conserve su derecha");

        buttonGroup14.add(jRadioButton262);
        jRadioButton262.setText("Vuelta obligatoria");

        jLabel311.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel311.setForeground(new java.awt.Color(0, 0, 0));
        jLabel311.setText("Pregunta 15");

        jLabel312.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel312.setForeground(new java.awt.Color(0, 0, 0));
        jLabel312.setText("¿Quien significa este otro?");

        buttonGroup15.add(jRadioButton263);
        jRadioButton263.setText("Preferencia de paso");

        buttonGroup15.add(jRadioButton264);
        jRadioButton264.setText("Alto");

        buttonGroup15.add(r15);
        r15.setText("Ceda el paso");

        jLabel313.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel313.setForeground(new java.awt.Color(0, 0, 0));
        jLabel313.setText("¿que vehiculos tienen preferencia de paso?");

        jLabel314.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel314.setForeground(new java.awt.Color(0, 0, 0));
        jLabel314.setText("de una vía de acceso controlado?");

        jLabel315.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel315.setForeground(new java.awt.Color(0, 0, 0));
        jLabel315.setText("existe señalizacion?");

        jLabel316.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel316.setForeground(new java.awt.Color(0, 0, 0));
        jLabel316.setText("mientras conduces?");

        jLabel317.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel317.setForeground(new java.awt.Color(0, 0, 0));
        jLabel317.setText("estacionado del limite de las vias o calles en zonas urbanas?");

        jButton5.setBackground(new java.awt.Color(0, 100, 168));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Finalizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese Curp ");

        jButton1.setText("prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel284, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel313, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel314, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel315, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel316, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel317, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton237, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton238, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton239, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton240, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton242, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton241, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton244, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton243, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton246, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton245, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton247, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton248, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton250, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton249, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton251, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton252, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r9, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton253, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton254, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r10, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r11, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton256, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton255, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton257, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton258, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r12, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r13, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton260, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton259, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r14, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton262, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton261, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton264, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r15, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton263, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(231, 231, 231)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel285)
                                            .addComponent(jLabel287)
                                            .addComponent(jLabel289)
                                            .addComponent(jLabel291)
                                            .addComponent(jLabel293)
                                            .addComponent(jLabel295)
                                            .addComponent(jLabel297)
                                            .addComponent(jLabel299)
                                            .addComponent(jLabel301)
                                            .addComponent(jLabel303)
                                            .addComponent(jLabel305)
                                            .addComponent(jLabel307)
                                            .addComponent(jLabel309)
                                            .addComponent(jLabel311)))
                                    .addComponent(jRadioButton236, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel286, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel288, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel290, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel292, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel294, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel296, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel298, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel300, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel302, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel304, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel306, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel308, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel310, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel312, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(ceda25, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(ceda24, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(jLabel283))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curp)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel283)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel284)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton236)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton237)
                .addGap(18, 18, 18)
                .addComponent(r1)
                .addGap(18, 18, 18)
                .addComponent(jLabel285)
                .addGap(18, 18, 18)
                .addComponent(jLabel286)
                .addGap(30, 30, 30)
                .addComponent(r2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton238)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton239)
                .addGap(18, 18, 18)
                .addComponent(jLabel287)
                .addGap(18, 18, 18)
                .addComponent(jLabel288)
                .addGap(1, 1, 1)
                .addComponent(jLabel313)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton240)
                .addGap(18, 18, 18)
                .addComponent(r3)
                .addGap(59, 59, 59)
                .addComponent(jLabel289)
                .addGap(18, 18, 18)
                .addComponent(jLabel290)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton241)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton242)
                .addGap(18, 18, 18)
                .addComponent(r4)
                .addGap(18, 18, 18)
                .addComponent(jLabel291)
                .addGap(18, 18, 18)
                .addComponent(jLabel292)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton243)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton244)
                .addGap(18, 18, 18)
                .addComponent(r5)
                .addGap(18, 18, 18)
                .addComponent(jLabel293)
                .addGap(18, 18, 18)
                .addComponent(jLabel294)
                .addGap(1, 1, 1)
                .addComponent(jLabel314)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton245)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton246)
                .addGap(18, 18, 18)
                .addComponent(r6)
                .addGap(18, 18, 18)
                .addComponent(jLabel295)
                .addGap(18, 18, 18)
                .addComponent(jLabel296)
                .addGap(1, 1, 1)
                .addComponent(jLabel315)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton247)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton248)
                .addGap(18, 18, 18)
                .addComponent(jLabel297)
                .addGap(18, 18, 18)
                .addComponent(jLabel298)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton249)
                .addGap(18, 18, 18)
                .addComponent(r8)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton250)
                .addGap(18, 18, 18)
                .addComponent(jLabel299)
                .addGap(18, 18, 18)
                .addComponent(jLabel300)
                .addGap(30, 30, 30)
                .addComponent(r9)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton251)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton252)
                .addGap(18, 18, 18)
                .addComponent(jLabel301)
                .addGap(18, 18, 18)
                .addComponent(jLabel302)
                .addGap(30, 30, 30)
                .addComponent(r10)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton253)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton254)
                .addGap(18, 18, 18)
                .addComponent(jLabel303)
                .addGap(18, 18, 18)
                .addComponent(jLabel304)
                .addGap(1, 1, 1)
                .addComponent(jLabel316)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton255)
                .addGap(18, 18, 18)
                .addComponent(r11)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton256)
                .addGap(18, 18, 18)
                .addComponent(jLabel305)
                .addGap(18, 18, 18)
                .addComponent(jLabel306)
                .addGap(30, 30, 30)
                .addComponent(r12)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton257)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton258)
                .addGap(18, 18, 18)
                .addComponent(jLabel307)
                .addGap(18, 18, 18)
                .addComponent(jLabel308)
                .addGap(1, 1, 1)
                .addComponent(jLabel317)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton259)
                .addGap(18, 18, 18)
                .addComponent(r13)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton260)
                .addGap(18, 18, 18)
                .addComponent(jLabel309)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel310)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ceda24, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton261)
                .addGap(18, 18, 18)
                .addComponent(r14)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton262)
                .addGap(18, 18, 18)
                .addComponent(jLabel311)
                .addGap(18, 18, 18)
                .addComponent(jLabel312)
                .addGap(37, 37, 37)
                .addComponent(ceda25, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton263)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton264)
                .addGap(18, 18, 18)
                .addComponent(r15)
                .addGap(31, 31, 31)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jScrollPane4.setViewportView(jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void res12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res12ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void res4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res4ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed
   Connection conn;
   int acc;
    void Conexion(){
     
         try {
                
            String user = "u795221605_root1";
            String pass = "rootadmin";
              String url = "jdbc:mysql://213.190.6.85:3306/u795221605_licencias_tam";
             Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection (url, user, pass);
            stm= conn.createStatement();
            stm1 =conn.createStatement();
           stm2=conn.createStatement();
            
        }
        catch ( ClassNotFoundException e ) {
            System.out.println(e);
        }
        catch(SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Verifique su conexion a internet o consulte al administrador");
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String ev="";
        if(curp.getText()!=ev){
              acc=0;
        if(r1.isSelected())      {
            acc++;
        }
         if(r2.isSelected())      {
            acc++;
        }
          if(r3.isSelected())      {
            acc++;
        }
           if(r4.isSelected())      {
            acc++;
        }
            if(r5.isSelected())      {
            acc++;
        }
             if(r6.isSelected())      {
            acc++;
        }
              if(r7.isSelected())      {
            acc++;
        }
               if(r8.isSelected())      {
            acc++;
        }
                if(r9.isSelected())      {
            acc++;
        }
                 if(r10.isSelected())      {
            acc++;
        }
                  if(r11.isSelected())      {
            acc++;
        }
                   if(r12.isSelected())      {
            acc++;
        }
                    if(r13.isSelected())      {
            acc++;
        }
                     if(r14.isSelected())      {
            acc++;
        }
                      if(r15.isSelected())      {
            acc++;
        }
                      
                    
                      
        
       try {  
           Conexion();
           rs=stm1.executeQuery("SELECT examen FROM ciudadano WHERE curp='"+curp.getText()+"'");
                   if(rs.next()){
                       if(rs.getInt(1)==0){
                           if(acc>=13){
                               stm2.executeUpdate("UPDATE ciudadano SET examen = 2  WHERE curp= '"+curp.getText()+"';");
                                JOptionPane.showMessageDialog(this,"Se han obtenido "+acc+" Aciertos, se ha aprovado el examen");
                                
                           }
                           else if(acc<13){
                                JOptionPane.showMessageDialog(this,"Se han obtenido "+acc+" Aciertos, NO se ha aprovado el examen");
                           }
                       }
                       else if(rs.getInt(1)==3){
                           if(acc==15){  
                               stm2.executeUpdate("UPDATE ciudadano SET examen = 2  WHERE curp= '"+curp.getText()+"';");
                               JOptionPane.showMessageDialog(this,"Se han obtenido "+acc+" Aciertos, se ha aprovado el examen");
                             
                           }
                           else{
                                JOptionPane.showMessageDialog(this,"Se han obtenido "+acc+" Aciertos, NO se ha aprovado el examen");
                           }
                       }
                }
   
               dispose();
            
                     
       } catch (SQLException ex) {
           System.out.println(ex);
       }
       
        }
        else{
            JOptionPane.showMessageDialog(this,"Favor De ingresar curp");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
r1.setSelected(true);
r2.setSelected(true);
r3.setSelected(true);
r4.setSelected(true);
r5.setSelected(true);
r6.setSelected(true);
r7.setSelected(true);
r8.setSelected(true);
r9.setSelected(true);
r10.setSelected(true);
r11.setSelected(true);
r12.setSelected(true);
r13.setSelected(true);
r14.setSelected(true);
r15.setSelected(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel ceda24;
    private javax.swing.JLabel ceda25;
    private javax.swing.JTextField curp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel283;
    private javax.swing.JLabel jLabel284;
    private javax.swing.JLabel jLabel285;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel288;
    private javax.swing.JLabel jLabel289;
    private javax.swing.JLabel jLabel290;
    private javax.swing.JLabel jLabel291;
    private javax.swing.JLabel jLabel292;
    private javax.swing.JLabel jLabel293;
    private javax.swing.JLabel jLabel294;
    private javax.swing.JLabel jLabel295;
    private javax.swing.JLabel jLabel296;
    private javax.swing.JLabel jLabel297;
    private javax.swing.JLabel jLabel298;
    private javax.swing.JLabel jLabel299;
    private javax.swing.JLabel jLabel300;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel302;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JLabel jLabel307;
    private javax.swing.JLabel jLabel308;
    private javax.swing.JLabel jLabel309;
    private javax.swing.JLabel jLabel310;
    private javax.swing.JLabel jLabel311;
    private javax.swing.JLabel jLabel312;
    private javax.swing.JLabel jLabel313;
    private javax.swing.JLabel jLabel314;
    private javax.swing.JLabel jLabel315;
    private javax.swing.JLabel jLabel316;
    private javax.swing.JLabel jLabel317;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JRadioButton jRadioButton236;
    private javax.swing.JRadioButton jRadioButton237;
    private javax.swing.JRadioButton jRadioButton238;
    private javax.swing.JRadioButton jRadioButton239;
    private javax.swing.JRadioButton jRadioButton240;
    private javax.swing.JRadioButton jRadioButton241;
    private javax.swing.JRadioButton jRadioButton242;
    private javax.swing.JRadioButton jRadioButton243;
    private javax.swing.JRadioButton jRadioButton244;
    private javax.swing.JRadioButton jRadioButton245;
    private javax.swing.JRadioButton jRadioButton246;
    private javax.swing.JRadioButton jRadioButton247;
    private javax.swing.JRadioButton jRadioButton248;
    private javax.swing.JRadioButton jRadioButton249;
    private javax.swing.JRadioButton jRadioButton250;
    private javax.swing.JRadioButton jRadioButton251;
    private javax.swing.JRadioButton jRadioButton252;
    private javax.swing.JRadioButton jRadioButton253;
    private javax.swing.JRadioButton jRadioButton254;
    private javax.swing.JRadioButton jRadioButton255;
    private javax.swing.JRadioButton jRadioButton256;
    private javax.swing.JRadioButton jRadioButton257;
    private javax.swing.JRadioButton jRadioButton258;
    private javax.swing.JRadioButton jRadioButton259;
    private javax.swing.JRadioButton jRadioButton260;
    private javax.swing.JRadioButton jRadioButton261;
    private javax.swing.JRadioButton jRadioButton262;
    private javax.swing.JRadioButton jRadioButton263;
    private javax.swing.JRadioButton jRadioButton264;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
